apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: cm9vdA==
  password: MDExMjIwMDM=
  postdb_uri: bW9uZ29kYitzcnY6Ly9hZG1pbjowMTEyMjAwM0Btb3Rpb24tYXNzaXN0cy53bTc1ZHZiLm1vbmdvZGIubmV0L21vdGlvbi1hcGktZGI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9TW90aW9uLUFzc2lzdHM=
  commentdb_uri: bW9uZ29kYitzcnY6Ly9hZG1pbjowMTEyMjAwM0Btb3Rpb24tYXNzaXN0cy53bTc1ZHZiLm1vbmdvZGIubmV0L21vdGlvbi1hcGktZGI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9TW90aW9uLUFzc2lzdHM=
  authdb_uri: bW9uZ29kYitzcnY6Ly9hZG1pbjowMTEyMjAwM0Btb3Rpb24tYXNzaXN0cy53bTc1ZHZiLm1vbmdvZGIubmV0L21vdGlvbi1hcGktZGI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9TW90aW9uLUFzc2lzdHM=


# Example URI: mongodb://root:01122003@postdb-svc:27017
