apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: cm9vdA==
  password: MDExMjIwMDM=
  postdb_uri: bW9uZ29kYitzcnY6Ly9hZG1pbjowMTEyMjAwM0Btb3Rpb24tY2x1c3Rlci45bHM2MS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9TW90aW9uLUNsdXN0ZXI=
  commentdb_uri: bW9uZ29kYitzcnY6Ly9hZG1pbjowMTEyMjAwM0Btb3Rpb24tY2x1c3Rlci45bHM2MS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9TW90aW9uLUNsdXN0ZXI=
  authdb_uri: bW9uZ29kYitzcnY6Ly9hZG1pbjowMTEyMjAwM0Btb3Rpb24tY2x1c3Rlci45bHM2MS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9TW90aW9uLUNsdXN0ZXI=


# Example URI: mongodb://root:01122003@postdb-svc:27017
